name: wedge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.3+13

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  intl_utils: ^2.8.4
  equatable: ^2.0.5
#  data_connection_checker: ^0.3.4
  page_view_indicators: ^2.0.0
  country_currency_pickers: ^3.0.0
  country_picker: ^2.0.21
  get_it: ^7.6.4
  fl_chart: 0.36.4
  flutter_bloc: 7.3.3
  bloc_test: ^8.5.0
  dartz: ^0.10.1
  mockito: ^5.4.2
  google_fonts:
  shared_preferences: ^2.2.1
  dio: ^5.3.2
  connectivity: ^3.0.6
  image_picker: ^1.0.4
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.9
  webview_flutter: 2.8.0
  jwt_decode: ^0.3.1
  charts_flutter: ^0.12.0
  jiffy: ^6.2.1
  flutter_echarts: ^2.3.0
  firebase_crashlytics: ^3.3.6
  firebase_analytics:  ^10.5.0
  firebase_messaging: ^14.6.8
  firebase_core: ^2.16.0
  wiredash: ^1.7.4
  permission_handler: ^10.4.5
  package_info_plus: ^4.1.0
  jwt_decoder: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  file_picker: ^5.5.0
  path_provider:
  downloads_path_provider_28: ^0.1.2
  url_launcher:  ^6.1.14
  flutter_local_notifications:  ^15.1.1
  amplitude_flutter: ^3.16.0
  local_auth: ^2.1.7
  pin_code_fields: ^8.0.1
  http: ^1.1.0
  mixpanel_flutter: ^2.1.1
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  upgrader: ^8.1.0
  calendar_date_picker2: ^0.5.3
  firebase_dynamic_links: ^5.3.6
  csv: ^5.0.2
  scoped_storage: ^0.0.1
  to_csv: ^2.1.0
  simple_tooltip: ^1.2.0
  open_file: ^3.3.2
  device_info_plus: ^9.0.3
  flutter_dash: ^1.0.0
  flutter_animated_icons: ^1.0.1
  badges: ^3.1.1
  showcaseview: 2.0.0
  custom_social_share: ^1.0.7
  share_plus:
  font_awesome_flutter: ^10.4.0
  lottie: ^1.4.3
  graphic: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  platform: ^3.1.2
  firebase_core_platform_interface: 4.8.0
  intl: any

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carousel/
    - assets/icons/
    - assets/icons/drawerIcons/
    - assets/placeholders/
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        #  weight: 400
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        #  weight: 600
        - asset: fonts/Poppins/Poppins-Black.ttf
        #  weight: 400
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
          #  weight: 900
          style: italic
        - asset: fonts/Poppins/Poppins-Medium.ttf
        #  weight: 500
        - asset: fonts/Poppins/Poppins-Thin.ttf
        #  weight: 500
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
          #  weight: 500
          style: italic
    # - family: Rubik
    #   fonts:
    #    - asset: fonts/Rubik-Black.ttf
    #     #  weight: 900
    #    - asset: fonts/Rubik-BlackItalic.ttf
    #     #  weight: 900
    #      style: italic
    #    - asset: fonts/Rubik-Medium.ttf
    #     #  weight: 500
    #    - asset: fonts/Rubik-MediumItalic.ttf
    #     #  weight: 500
    #      style: italic



