import 'package:wedge/core/common/domain/usecases/excel_download.dart';
import 'package:wedge/core/common/domain/usecases/refresh_aggregator_usecase.dart';
import 'package:wedge/dependency_injection.dart';
import 'package:wedge/features/aggregation_results/domain/usecase/getAggregationResults.dart';
import 'package:wedge/features/all_accounts_types/domain/usecases/get_assets_usecase.dart';
import 'package:wedge/features/all_accounts_types/domain/usecases/get_liabilites_usecase.dart';
import 'package:wedge/features/app_passcode/create_passcode/domain/usecase/create_passcode_usecase.dart';
import 'package:wedge/features/assets/all_assets/domain/usecases/get_all_assets.dart';
import 'package:wedge/features/assets/assets_liablities_main/domain/usecases/get_all_assets.dart';
import 'package:wedge/features/assets/assets_liablities_main/domain/usecases/get_all_liabilities.dart';
import 'package:wedge/features/assets/bank_account/add_bank_account/domain/usecases/get_providers.dart';
import 'package:wedge/features/assets/bank_account/add_bank_account/domain/usecases/get_top_institutes.dart';
import 'package:wedge/features/assets/bank_account/add_bank_manual/domain/usecases/add_manual_bank_usecase.dart';
import 'package:wedge/features/assets/bank_account/add_bank_manual/domain/usecases/update_manual_bank_usecase.dart';
import 'package:wedge/features/assets/bank_account/bank_accounts/domain/usecases/get_home_bank_accounts.dart';
import 'package:wedge/features/assets/bank_account/bank_accounts/domain/usecases/get_manual_transaction_details.dart';
import 'package:wedge/features/assets/bank_account/bank_accounts/domain/usecases/get_transaction_details.dart';
import 'package:wedge/features/assets/bank_account/bank_accounts/domain/usecases/refresh_aggregator_account.dart';
import 'package:wedge/features/assets/bank_account/bank_accounts/domain/usecases/update_manual_bank_balance_sheet.dart';
import 'package:wedge/features/assets/bank_account/bank_success_screen/domain/usecase/get_account_data_usecase.dart';
import 'package:wedge/features/assets/bank_account/main_bank_account/domain/usecases/delete_bank_account.dart';
import 'package:wedge/features/assets/bank_account/main_bank_account/domain/usecases/get_bank_accounts.dart';
import 'package:wedge/features/assets/bank_account/userdata_summery/domain/usecases/get_hoxtondata_summery.dart';
import 'package:wedge/features/assets/bank_account/userdata_summery/domain/usecases/get_user_details.dart';
import 'package:wedge/features/assets/bank_account/yodlee_frame/domain/usecases/get_yodlee_token.dart';
import 'package:wedge/features/assets/crypto/add_crypto_manual/domain/usecases/add_cryto_usecase.dart';
import 'package:wedge/features/assets/crypto/add_crypto_manual/domain/usecases/udpate_cryto_usecase.dart';
import 'package:wedge/features/assets/crypto/crypto_main/domain/usecase/delete_crypto_usecase.dart';
import 'package:wedge/features/assets/crypto/crypto_main/domain/usecase/get_crypto_usecase.dart';
import 'package:wedge/features/assets/crypto/crypto_search/domain/usecases/get_crypto_currency.dart';
import 'package:wedge/features/assets/crypto/crypto_search/domain/usecases/get_crypto_data.dart';
import 'package:wedge/features/assets/custom_assets/add_custom_assets/domain/usecases/add_custom_assets_usecase.dart';
import 'package:wedge/features/assets/custom_assets/add_custom_assets/domain/usecases/update_custom_assets_usecase.dart';
import 'package:wedge/features/assets/custom_assets/custom_assets_drop_down/domain/usecases/get_custom_assets_drop_down.dart';
import 'package:wedge/features/assets/custom_assets/custom_assets_main/domain/usecases/delete_custom_assets.dart';
import 'package:wedge/features/assets/custom_assets/custom_assets_main/domain/usecases/get_custom_assets.dart';
import 'package:wedge/features/assets/invesntment/add_investment_manual/domain/usecases/add_investment_usecase.dart';
import 'package:wedge/features/assets/invesntment/add_investment_manual/domain/usecases/update_investment_usecase.dart';
import 'package:wedge/features/assets/invesntment/investment_main/domain/usecases/delete_investment_usecase.dart';
import 'package:wedge/features/assets/invesntment/investment_main/domain/usecases/get_investments_usecase.dart';
import 'package:wedge/features/assets/pension/add_pension_manual/domain/usercase/add_manual_pension.dart';
import 'package:wedge/features/assets/pension/add_pension_manual/domain/usercase/update_manual_pension.dart';
import 'package:wedge/features/assets/pension/pension_main/domain/usecases/delete_pension_usecase.dart';
import 'package:wedge/features/assets/pension/pension_main/domain/usecases/get_pension_usecase.dart';
import 'package:wedge/features/assets/pension_investment/pension_investments_main/domain/usecases/get_insights.dart';
import 'package:wedge/features/assets/pension_investment/pension_investments_main/domain/usecases/get_pension_investment_main.dart';
import 'package:wedge/features/assets/properties/add_properties/domain/usecases/add_property_usecase.dart';
import 'package:wedge/features/assets/properties/add_properties/domain/usecases/update_property_usecase.dart';
import 'package:wedge/features/assets/properties/properties_main/domain/usecases/delete_properties.dart';
import 'package:wedge/features/assets/properties/properties_main/domain/usecases/get_properties.dart';
import 'package:wedge/features/assets/properties/properties_main/domain/usecases/unlink_properties_usecase.dart';
import 'package:wedge/features/assets/stocks/add_stcoks/domain/usecases/add_custom_assets_usecase.dart';
import 'package:wedge/features/assets/stocks/add_stcoks/domain/usecases/update_custom_assets_usecase.dart';
import 'package:wedge/features/assets/stocks/search_stocks/domain/usecases/get_search_stocks.dart';
import 'package:wedge/features/assets/stocks/search_stocks/domain/usecases/get_stocks_currency.dart';
import 'package:wedge/features/assets/stocks/stocks_main/domain/usecases/delete_stocks_usecase.dart';
import 'package:wedge/features/assets/stocks/stocks_main/domain/usecases/get_stocks_usecase.dart';
import 'package:wedge/features/assets/vehicle/add_vehicle/domain/usecases/add_vehicle_usecase.dart';
import 'package:wedge/features/assets/vehicle/add_vehicle/domain/usecases/update_vehicle_usecase.dart';
import 'package:wedge/features/assets/vehicle/vehicle_main/domain/usecases/delete_vehicle_usecase.dart';
import 'package:wedge/features/assets/vehicle/vehicle_main/domain/usecases/get_vehicles_usecase.dart';
import 'package:wedge/features/assets/vehicle/vehicle_main/domain/usecases/unlink_vehicle_usecase.dart';
import 'package:wedge/features/auth/create_password/domain/usecases/create_password_usecase.dart';
import 'package:wedge/features/auth/hoxton_login/domain/usecases/login.dart';
import 'package:wedge/features/auth/hoxton_login/domain/usecases/resend_code_usecase.dart';
import 'package:wedge/features/auth/hoxton_login/domain/usecases/reset_password.dart';
import 'package:wedge/features/auth/hoxton_login/domain/usecases/validate_otp_usecase.dart';
import 'package:wedge/features/auth/hoxton_login/domain/usecases/verify_email_usecase.dart';
import 'package:wedge/features/auth/terms_and_condition/domain/usecase/accept_term_condition_usecase.dart';
import 'package:wedge/features/beneficiary/beneficiary_add/domain/usecases/add_beneficiary_member_usecase.dart';
import 'package:wedge/features/beneficiary/beneficiary_add/domain/usecases/edit_beneficiary_member_usecase.dart';
import 'package:wedge/features/beneficiary/beneficiary_trusted_main/domain/usecase/delete_beneficiary_member.dart';
import 'package:wedge/features/beneficiary/beneficiary_trusted_main/domain/usecase/delete_trusted_member.dart';
import 'package:wedge/features/beneficiary/beneficiary_trusted_main/domain/usecase/get_beneficiary.dart';
import 'package:wedge/features/beneficiary/beneficiary_trusted_main/domain/usecase/get_trusted_members.dart';
import 'package:wedge/features/beneficiary/trusted_add/domain/usecases/add_trusted_member_usecase.dart';
import 'package:wedge/features/beneficiary/trusted_add/domain/usecases/edit_trusted_member_usecase.dart';
import 'package:wedge/features/calculators/retirement_calculator/domain/usecases/get_calculator_insights.dart';
import 'package:wedge/features/change_passcode/domain/usecases/change_passcode_usecase.dart';
import 'package:wedge/features/change_password/domain/usecases/change_password_usecase.dart';
import 'package:wedge/features/home/domain/usecase/get_dashboard_usecase.dart';
import 'package:wedge/features/liabilities/add_liabilities_page/domain/usecase/get_liabilities_usecase.dart';
import 'package:wedge/features/liabilities/credit_card/add_credit_card_debt/domain/usecase/add_credit_cards_usecase.dart';
import 'package:wedge/features/liabilities/credit_card/add_credit_card_debt/domain/usecase/update_credit_cads_usecase.dart';
import 'package:wedge/features/liabilities/credit_card/credit_card_debt_main/domain/usecase/delete_credit_card.dart';
import 'package:wedge/features/liabilities/credit_card/credit_card_debt_main/domain/usecase/get_credit_card.dart';
import 'package:wedge/features/liabilities/mortgages/add_mortgages/domain/usecases/add_mortgages_usecases.dart';
import 'package:wedge/features/liabilities/mortgages/add_mortgages/domain/usecases/update_mortgages_usecase.dart';
import 'package:wedge/features/liabilities/mortgages/mortgages_main/domain/usecases/delete_mortage_usecase.dart';
import 'package:wedge/features/liabilities/mortgages/mortgages_main/domain/usecases/get_mortage_usecase.dart';
import 'package:wedge/features/liabilities/mortgages/mortgages_main/domain/usecases/unlink_mortage_usecase.dart';
import 'package:wedge/features/liabilities/other_liabilities/add_other_liabilities/domain/usecases/add_other_liabilities_usecase.dart';
import 'package:wedge/features/liabilities/other_liabilities/add_other_liabilities/domain/usecases/update_other_liabilities_usecase.dart';
import 'package:wedge/features/liabilities/other_liabilities/other_liabilities_main/domain/usecases/delete_other_liabilities_usecase.dart';
import 'package:wedge/features/liabilities/other_liabilities/other_liabilities_main/domain/usecases/get_other_liabilities_usecase.dart';
import 'package:wedge/features/liabilities/personal_loan/add_personal_loan/domain/use_cases/add_personal_loan_use_case.dart';
import 'package:wedge/features/liabilities/personal_loan/add_personal_loan/domain/use_cases/update_personal_load_usecase.dart';
import 'package:wedge/features/liabilities/personal_loan/personal_loan_main/domain/usecase/delete_main_personal_loan.dart';
import 'package:wedge/features/liabilities/personal_loan/personal_loan_main/domain/usecase/get_main_personal_loan.dart';
import 'package:wedge/features/liabilities/vehicle_loan/add_vehicle_loan/domain/usecase/add_vehicle_loans_usecase.dart';
import 'package:wedge/features/liabilities/vehicle_loan/add_vehicle_loan/domain/usecase/udpate_vehicle_loans_usecase.dart';
import 'package:wedge/features/liabilities/vehicle_loan/vehicle_loan_main/domain/usecases/delete_vehicle_loans.dart';
import 'package:wedge/features/liabilities/vehicle_loan/vehicle_loan_main/domain/usecases/get_vehicle_loans.dart';
import 'package:wedge/features/liabilities/vehicle_loan/vehicle_loan_main/domain/usecases/unlink_vehicle_loans.dart';
import 'package:wedge/features/support/domain/usecases/add_support_account_usecase.dart';
import 'package:wedge/features/user_services/generic_domain/generic_usecases/download_doc_usecase.dart';
import 'package:wedge/features/user_services/generic_domain/generic_usecases/get_advisor_plugin.dart';
import 'package:wedge/features/user_services/generic_domain/generic_usecases/get_documents_usecase.dart';
import 'package:wedge/features/user_services/generic_domain/generic_usecases/get_pension_report_usecase.dart';
import 'package:wedge/features/user_services/generic_domain/generic_usecases/get_plugins.dart';
import 'package:wedge/features/wealth_vault/documents/domain/usecases/download_document.dart';
import 'package:wedge/features/wealth_vault/documents/domain/usecases/get_document.dart';
import 'package:wedge/features/your_investments/domain/usecases/get_holdings.dart';
import 'package:wedge/features/your_pensions/domain/usecases/get_holdings.dart';

import '../core/common/domain/usecases/get_notification_banner_usecase.dart';
import '../core/common/domain/usecases/update_notification_banner_usecase.dart';
import '../core/common/line_performance_graph/domain/repository/line_Performance_graph_repository.dart';
import '../features/account/my_account/domain/usecase/edit_user_account_usecase.dart';
import '../features/account/my_account/domain/usecase/edit_user_preference_usecase.dart';
import '../features/account/my_account/domain/usecase/get_tenant_usecase.dart';
import '../features/account/my_account/domain/usecase/get_user_account_usecase.dart';
import '../features/account/my_account/domain/usecase/get_user_preference_usecase.dart';
import '../features/account/third_party_access/domain/usecase/third_party_access_usecase.dart';
import '../features/assets/assets_liablities_main/domain/usecases/get_all_assets_libilities.dart';
import '../features/assets/bank_account/main_bank_account/domain/repositories/get_bank_accounts_repository.dart';
import '../features/auth/hoxton_login/domain/usecases/login_with_otp.dart';
import '../features/auth/personal_details/domain/usecases/personal_details_usecase.dart';
import '../features/auth/signup/domain/usecases/login_with_token.dart';
import '../features/auth/signup/domain/usecases/signup_details_usecase.dart';
import '../features/auth/signup/domain/usecases/validate_user_details_usecase.dart';
import '../features/home/domain/usecase/get_disconnected_accouts_usecase.dart';
import '../features/invite_friends/domain/usecase/get_invite_friends_usecase.dart';
import '../features/liabilities/credit_card/credit_card_debt_main/domain/repository/credit_card_repository.dart';
import '../features/user_services/uplead_documents/domain/usecases/download_uploaded_document_usecase.dart';
import '../features/user_services/uplead_documents/domain/usecases/get_upload_document_folders_usecase.dart';
import '../features/user_services/uplead_documents/domain/usecases/get_uploaded_document_usecase.dart';
import '../features/user_services/uplead_documents/domain/usecases/upload_document_usecase.dart';
import '../features/wealth_vault/documents/domain/usecases/delete_documents.dart';
import '../features/wealth_vault/documents/domain/usecases/upload_document.dart';
import '../features/your_investments/domain/usecases/edit_investment_notes_usecase.dart';
import '../features/your_pensions/domain/usecases/edit_pension_notes_usecase.dart';

class RegisterUseCases {
  RegisterUseCases() {
    locator.registerLazySingleton(() => VerifyEmail(locator()));
    locator.registerLazySingleton(() => LoginUser(locator()));
    locator.registerLazySingleton(() => ResetPassword(locator()));
    locator.registerLazySingleton(() => GetHoxtonUserDataSummery(locator()));
    locator.registerLazySingleton(() => GetMainAssets(locator()));
    locator.registerLazySingleton(() => GetAllAssets(locator()));
    locator.registerLazySingleton(() => AddManualBankAccount(locator()));
    locator.registerLazySingleton(() => GetBankAccounts(locator()));
    locator.registerLazySingleton(() => UpdateManualBankAccount(locator()));
    locator.registerLazySingleton(() => DeleteBankAccounts(locator()));
    locator.registerLazySingleton(() => GetUserDetails(locator()));
    locator.registerLazySingleton(() => GetCustomAssets(locator()));
    locator.registerLazySingleton(() => DeleteCustomAssets(locator()));
    locator.registerLazySingleton(() => AddCustomAssets(locator()));
    locator.registerLazySingleton(() => UpdateCustomAssets(locator()));
    locator.registerLazySingleton(() => GetProperties(locator()));
    locator.registerLazySingleton(() => DeleteProperties(locator()));
    locator.registerLazySingleton(() => AddProperty(locator()));
    locator.registerLazySingleton(() => UpdateProperty(locator()));
    locator.registerLazySingleton(() => AddStocksBonds(locator()));
    locator.registerLazySingleton(() => UpdateStocksBonds(locator()));
    locator.registerLazySingleton(() => GetStocks(locator()));
    locator.registerLazySingleton(() => DeleteStocksBonds(locator()));
    locator.registerLazySingleton(() => GetInvestments(locator()));
    locator.registerLazySingleton(() => DeleteInvestment(locator()));
    locator.registerLazySingleton(() => AddInvestment(locator()));
    locator.registerLazySingleton(() => UpdateInvestment(locator()));
    locator.registerLazySingleton(() => GetVehicless(locator()));
    locator.registerLazySingleton(() => DeleteVehicles(locator()));
    locator.registerLazySingleton(() => AddVehicle(locator()));
    locator.registerLazySingleton(() => UpdateVehicle(locator()));
    locator.registerLazySingleton(() => AddPersonalLoan(locator()));
    locator.registerLazySingleton(() => AddManualPensionUsecase(locator()));
    locator.registerLazySingleton(() => UpdateManualPensionsUseCase(locator()));
    locator.registerLazySingleton(() => GetPensionsUseCase(locator()));
    locator.registerLazySingleton(() => DeletePensionUsecase(locator()));
    locator.registerLazySingleton(() => GetMainPersonalLoanUsecase(locator()));
    locator.registerLazySingleton(() => GetMainLiabilities(locator()));
    locator.registerLazySingleton(() => UpdatePersonLoan(locator()));
    locator
        .registerLazySingleton(() => DeleteMainPersonalLoanUsecase(locator()));
    locator.registerLazySingleton(() => GetLiabilities(locator()));
    locator.registerLazySingleton(() => GetCryptoDataUsecase(locator()));
    locator.registerLazySingleton(() => DeleteCryptoUsecase(locator()));
    locator.registerLazySingleton(() => AddCryptoUsecase(locator()));
    locator.registerLazySingleton(() => UpdateCryptoUsecase(locator()));
    locator.registerLazySingleton(() => GetMainCreditCard(locator()));
    locator.registerLazySingleton(() => DeleteCreditCards(locator()));
    locator.registerLazySingleton(() => AddCreditCardsUsecase(locator()));
    locator.registerLazySingleton(() => UpdateCreditCardsUsecase(locator()));
    locator.registerLazySingleton(() => GetVehicleLoansUsecase(locator()));
    locator.registerLazySingleton(() => DeleteVehicleLoansUsecase(locator()));
    locator.registerLazySingleton(() => AddVehicleLoansUsecase(locator()));
    locator.registerLazySingleton(() => UpdateVehicleLoansUsecase(locator()));
    locator.registerLazySingleton(() => UnlinkVehicleLoans(locator()));
    locator.registerLazySingleton(() => GetMortageUsecase(locator()));
    locator.registerLazySingleton(() => DeleteMortageUsecase(locator()));
    locator.registerLazySingleton(() => UnlinkMortageUsecase(locator()));
    locator.registerLazySingleton(() => AddMortgagesUsecases(locator()));
    locator.registerLazySingleton(() => UpdateMortgagesUsecases(locator()));
    locator.registerLazySingleton(() => GetOtherLiabilitiesUsecase(locator()));
    locator
        .registerLazySingleton(() => DeleteOtherLiabilitiesUsecase(locator()));
    locator.registerLazySingleton(() => AddOtherLiabilitiesUsecase(locator()));
    locator
        .registerLazySingleton(() => UpdateOtherLiabilitiesUsecase(locator()));
    locator.registerLazySingleton(() => UnlinkVehicleUsecase(locator()));
    locator.registerLazySingleton(() => UnlinkProperties(locator()));
    locator.registerLazySingleton(() => GetAllAssetsMain(locator()));
    locator.registerLazySingleton(() => GetAllAssetsLiabilitiesMain(locator()));
    locator.registerLazySingleton(() => GetAllLiabilitiesMain(locator()));
    locator.registerLazySingleton(() => GetHomeBankAccounts(locator()));
    locator.registerLazySingleton(() => GetMainPensionInvestments(locator()));
    locator.registerLazySingleton(() => AddSupportAccountUsecase(locator()));
    locator.registerLazySingleton(() => GetUserAccountUseCase(locator()));
    locator.registerLazySingleton(() => EditUserAccountUseCase(locator()));
    locator.registerLazySingleton(() => GetCustomAssetsDropDown(locator()));
    locator.registerLazySingleton(() => GetCryptoCurrency(locator()));
    locator.registerLazySingleton(() => GetCryptoData(locator()));
    locator.registerLazySingleton(() => GetStocksData(locator()));
    locator.registerLazySingleton(() => GetStocksCurrency(locator()));
    locator.registerLazySingleton(() => GetProviders(locator()));
    locator.registerLazySingleton(() => GetTopInstitute(locator()));
    locator.registerLazySingleton(() => GetUserPreferenceUseCase(locator()));
    locator.registerLazySingleton(() => EditUserPreferencesUseCase(locator()));
    locator.registerLazySingleton(() => EditPensionNoteUseCase(locator()));
    locator.registerLazySingleton(() => EditInvestmentNoteUseCase(locator()));
    locator.registerLazySingleton(() => GetProviderToken(locator()));
    locator.registerLazySingleton(() => GetYodleeBankTransaction(locator()));
    locator.registerLazySingleton(() => GetManualBankTransaction(locator()));
    locator.registerLazySingleton(() => UpdateManualBalanceSheet(locator()));
    locator.registerLazySingleton(() => GetHoldings(locator()));
    locator.registerLazySingleton(
        () => GetMainPensionInvestmentsInsights(locator()));
    locator.registerLazySingleton(() => CreatePasswordUsecase(locator()));
    locator.registerLazySingleton(() => GetCalculatorInsights(locator()));
    locator.registerLazySingleton(() => GetDashboardData(locator()));
    locator
        .registerLazySingleton(() => GetBeneficiaryDetailsUsecase(locator()));
    locator.registerLazySingleton(() => GetTrustedDetailsUsecase(locator()));
    locator.registerLazySingleton(() => AddBeneficiaryUsecase(locator()));
    locator.registerLazySingleton(() => EditBeneficiaryUsecase(locator()));
    locator.registerLazySingleton(() => AddTrustedMemberUsecase(locator()));
    locator.registerLazySingleton(() => EditTrustedMemberUsecase(locator()));
    locator.registerLazySingleton(() => DeleteTrustedDetailsUsecase(locator()));
    locator.registerLazySingleton(
        () => DeleteBeneficiaryDetailsUsecase(locator()));
    locator.registerLazySingleton(() => GetDocument(locator()));
    locator.registerLazySingleton(() => DeleteDocument(locator()));
    locator.registerLazySingleton(() => UploadDocument(locator()));
    locator.registerLazySingleton(() => DownloadDocument(locator()));
    locator.registerLazySingleton(() => GetPlugins(locator()));
    locator.registerLazySingleton(() => GetUserAdvisorUsecase(locator()));
    locator.registerLazySingleton(() => GetDocumentUsecase(locator()));
    locator.registerLazySingleton(() => GetPensionReportUsecase(locator()));
    locator.registerLazySingleton(() => ServiceDownloadDocument(locator()));
    locator.registerLazySingleton(() => LoginWithOTP(locator()));
    locator.registerLazySingleton(() => LoginWithToken(locator()));
    locator.registerLazySingleton(() => ValidateOTPUsecase(locator()));
    locator.registerLazySingleton(() => ResendOTPusecase(locator()));
    locator.registerLazySingleton(() => GetHoldingsPension(locator()));
    locator.registerLazySingleton(() => GetPensionPerformance(locator()));
    locator.registerLazySingleton(() => GetCreditCardTransaction(locator()));
    locator
        .registerLazySingleton(() => GetCashAccountPiePerformance(locator()));
    locator
        .registerLazySingleton(() => GetCashAccountBarPerformance(locator()));
    locator.registerLazySingleton(() => GetCashAccountTransaction(locator()));
    locator.registerLazySingleton(() => GetLinePerformance(locator()));
    locator.registerLazySingleton(() => PersonalDetailsUseCase(locator()));
    locator.registerLazySingleton(() => UploadDocumentUseCase(locator()));
    locator.registerLazySingleton(() => GetCreditCardPiePerformance(locator()));
    locator.registerLazySingleton(() => GetStocksPerformance(locator()));
    locator.registerLazySingleton(() => GetCryptoPerformance(locator()));
    locator.registerLazySingleton(() => GetInvestmentPerformance(locator()));
    locator.registerLazySingleton(() => GetAggregationResultUsecase(locator()));
    locator.registerLazySingleton(() => RefreshAggregatorAccount(locator()));
    locator.registerLazySingleton(
        () => CommonRefreshAggregatorAccountUseCase(locator()));
    locator.registerLazySingleton(() => AcceptTermConditionUseCase(locator()));
    locator.registerLazySingleton(() => GetTenantUseCase(locator()));
    locator.registerLazySingleton(() => CreatePasscodeUseCase(locator()));
    locator.registerLazySingleton(() => ChangePasswordUsecase(locator()));
    locator.registerLazySingleton(() => ChangePasscodeUsecase(locator()));
    locator.registerLazySingleton(() => GetThirdPartyAccessUsecase(locator()));
    locator.registerLazySingleton(() => ExcelDownload(locator()));
    locator.registerLazySingleton(() => SignUpUseCase(locator()));
    locator.registerLazySingleton(() => ValidateUserDetailsUseCase(locator()));
    locator.registerLazySingleton(() =>
        DownloadUploadedDocumentUsecase(viewDocumentRepository: locator()));
    locator.registerLazySingleton(
        () => GetUploadedDocumentUsecase(viewDocumentRepository: locator()));
    locator.registerLazySingleton(() => GetUploadDocumentFoldersUsecase(
        uploadDocumentMainRepository: locator()));
    locator.registerLazySingleton(() => GetAccountDataUsecase(locator()));
    locator.registerLazySingleton(() => GetInviteFriendsData(locator()));
    locator
        .registerLazySingleton(() => GetDisconnectedAccountsUseCase(locator()));
    locator.registerLazySingleton(
        () => GetNotificationAndBannerUseCase(locator()));
    locator.registerLazySingleton(
        () => UpdateNotificationAndBannerUseCase(locator()));
  }
}
